### ISSUE TITLE
There is no documentation on how to use this

### ISSUE THREAD

**Issue by CasualTerror** [veevelder/random-encounters#1]
I have no idea how to use this module. This is nothing that says how it works or what we have to do to use it. Please explain the steps on how to use this module in Foundry VTT once it's installed.

**Comment by rapuhotelli** [comment]
Seconding this. "Random Encounters" as a module name is _very_ broad and there are as many ways to run random encounters as there are game masters! Show the readme some love :)

**Comment by veevelder** [comment]
I have added some documentation to the read me.
