### ISSUE TITLE
Deleting Everything

### ISSUE THREAD

**Issue by Centor1982** [veevelder/random-encounters#2]
So had this installed and all its subs and added a bunch of tokens tiles and journals to my maps. Everything was fine till I came back a couple of hours later and everything disappeared. I hadn't really even used the module so I started disabling mods and once this and its subs were disabled everything came back. Is this supposed to happen or an error? Thank you

**Comment by veevelder** [comment]
So I figured out the problem, it was due to some misspelled settings, I have a fix in the newest version that will now ask if you want to update the old settings to the new settings.
