### ISSUE TITLE
Installed but not showing in Foundry

### ISSUE THREAD

**Issue by moulson1313** [veevelder/random-encounters#3]
I installed the module however it does not show up in modules to ennoble.

**Comment by veevelder** [comment]
thanks for letting me know, can you tell me what version of Foundry VTT you are using, the version of random-encounters, and a list of other modules and their versions?

Also just to clarify, you can install the module but it doesnt show up in the `Module Management` window?

**Comment by moulson1313** [comment]
Correct when I pull up module management it does not show. Currently running Foundry Virtual Tabletop Version 9 build 269 (nice) running it with Pathfinder 2nd Edition 3.13.5.16.
Running Random Encounters v 0.2.
<img width="649" alt="Screenshot 2022-08-16 at 3 34 43 PM" src="https://user-images.githubusercontent.com/90971459/184966569-fe652554-fe97-497d-9ad5-9ba42f876d72.png">
2

**Comment by veevelder** [comment]
thanks for the info, ill check it out and let you know soon

**Comment by veevelder** [comment]
it was a simple fix, I intially had it only released for D&D 5e, removed that requirement and it should now show up! Also note that I haven't tested any other system with the module so things might be a bit buggy if you find any other issue let me know.

**Comment by moulson1313** [comment]
Thank you. I will let you know. Would you like it in this ticket or in a different one?

**Comment by veevelder** [comment]
Different one will be fine. Thanks and did the update work for you?

**Comment by veevelder** [comment]
is everything working for you, can I close the issue?
