### ISSUE TITLE
Update Random Encounters gives out Manifest Error

### ISSUE THREAD

**Issue by YorinLuz** [veevelder/random-encounters#5]
Hello,
since the V10 Foundry Update, I get this error when I try to update the Random Encounters module:
![Random Encounters](https://user-images.githubusercontent.com/95984260/190897617-462323d7-ec3a-4b86-8d62-c2a0e465b7ef.png)

**Comment by veevelder** [comment]
How are you updating the module?

That message is from https://github.com/veevelder/random-encounters/blob/main/module.json which is not the correct module.json. The correct one is https://github.com/veevelder/random-encounters/releases/download/0.2.5/module.json

The app should have picked up on the correct module.json file but if it didnt you can either use that correct link above or use https://github.com/veevelder/random-encounters/releases/latest/download/module.json which will always get the latest release.

**Comment by YorinLuz** [comment]
I just clicked on update in foundry. For others it changes the manifest, if it's not valid anymore, I didn't get the pop-up for it for your module.

**Comment by veevelder** [comment]
im not sure whats going on there, in my testing I was able to update from v9 to v10 with the module updating as well. However, I do know that if you uninstall Random Encounters and then re-install, it will save your settings. So you shouldnt have to recreate your encounters. Just make sure to resave them, after you re-install.

I hope this helps.
