### ISSUE TITLE
Allow random encounters to roll from RollTables in compendium packs

### ISSUE THREAD

**Issue by wyrmisis** [veevelder/random-encounters#6]
**Is your feature request related to a problem? Please describe.**
I want to use the same random encounter tables across multiple Worlds without having to import them from a compendium.

**Describe the solution you'd like**
I'd like to be able to select RollTables that are inside of compendiums.

**Describe alternatives you've considered**
If this isn't possible, I'd like to be able to manually enter a UUID for the RollTable I'd like the encounter to roll on.

**Comment by veevelder** [comment]
Thanks for the idea, it has been added in the new version, let me know if thats what you where expecting and/or if you encounter any bugs/issues.

**Comment by veevelder** [comment]
closing
