### ISSUE TITLE
Issue with encounters triggering after X amount of time

### ISSUE THREAD

**Issue by ghost** [veevelder/random-encounters#7]
I think there might be an issue with the about-time functionality with this module. Despite setting a 1-minute time duration with a guaranteed encounter I'm able to get any results back after the time elapses.

Below are some screenshots from my setup. I did check the console, but I didn't find any specific error messages. I am able to trigger the event via hot-hotkey.

![image](https://user-images.githubusercontent.com/33186688/202837730-b482a13a-e487-4402-be6d-02b326ecad9d.png)
![image](https://user-images.githubusercontent.com/33186688/202837753-0a5fbf0a-e8d0-4006-b8d9-7908477ec586.png)
![image](https://user-images.githubusercontent.com/33186688/202837777-3229150a-c060-4d4d-b5e7-0772c1f34a6e.png)
![image](https://user-images.githubusercontent.com/33186688/202837786-81ea5ecd-792e-47af-8c2e-3f601516f00a.png)

**Comment by veevelder** [comment]
Have you looked at https://github.com/veevelder/random-encounters/blob/main/about-time-issues.md? It details some issues and a possible fix I found. Let me know if that doesn't work I can take a look.

**Comment by jburrows127** [comment]
I get the following error when I try to run the first command from the console:

![image](https://user-images.githubusercontent.com/33186688/202885501-712a7da1-d76d-4fb8-b600-dcf245177b2e.png)

**Comment by ghost** [comment]
I ran the game.Gametime.queue() command in the console, and it said the queue was empty:
![image](https://user-images.githubusercontent.com/33186688/202885689-bd39caec-c350-408e-9f27-2d9fb50e7c33.png)

I followed the rest of the directions and resaved the encounter, and this time I did notice the following error message, although I'm not sure what to make of it.

![image](https://user-images.githubusercontent.com/33186688/202885982-33af9303-1b1b-469b-a382-de8a5c4c04e8.png)

**Comment by veevelder** [comment]
I should have it fixed in the newest release, let me know if this fixes it for you.

**Comment by ghost** [comment]
With the new release I'm able to get it to trigger like how I would expect. However, after I refresh it fails again with the follower error. 

![image](https://user-images.githubusercontent.com/33186688/204449199-94025fee-66c0-45c8-8f94-60b0a84a426f.png)

**Comment by veevelder** [comment]
sorry for taking so long on fixing this, but I do believe I have it fixed. Let me know if its working for you.
